### ISSUE TITLE
(Feature request) Visualize color data inside Texture3D

### ISSUE THREAD

**Issue by Looooong** [mattatz/unity-volume-rendering#2]

**Comment by neon-ninja** [comment]
hey @Looooong  - check out https://github.com/UoA-eResearch/DICOM_viewer/commit/cce182b9d47af348b7b7dea4d465c3c1da4e80e2 - I was able to tweak this shader to display color data with fairly minimal changes

**Comment by Looooong** [comment]
Thanks for the reference. I didn't figure out the alpha calculation step :sweat_smile:
