### ISSUE TITLE
Arbitrary slice position/angle? 

### ISSUE THREAD

**Issue by justinross** [mattatz/unity-volume-rendering#5]
Is it possible to have an arbitrary angle and position of the slice plane, rather than just orthogonal xyz?

**Comment by mattatz** [comment]
done!
You can rotate slice axes by setting an axis quaternion prop in VolumeRendering component 💯 
0f5e1a80d0eab7ae75a74c1dc39b077d7fd12edb

**Comment by justinross** [comment]
Cool, thanks! Playing with it now. :)
